sudo: true
dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - autoconf

before_install:
  - cd /tmp
  - git clone http://git.veripool.org/git/verilator
  - cd verilator
  - git checkout verilator_3_902
  - autoconf
  - ./configure
  - make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR

script:
  - verilator --lint-only rtl/verilog/*.v +incdir+rtl/verilog
